services:
  nginx:
    image: nginx:1.27.0
    container_name: my-nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    depends_on:
      - php-fpm


  php-fpm:
    image: php:fpm
    container_name: my-php-fpm
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres

  postgres:
    image: postgres:16.5
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: