#!/usr/bin/env php
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

use console\ConsoleApp;

require 'vendor/autoload.php';

$config = require 'console/config.php';
$app = new ConsoleApp($config);

// Отримуємо параметри з командного рядка
$arguments = $argv;
array_shift($arguments); // Видаляємо назву скрипта з аргументів

// Перевірка, що команда вказана
if (empty($arguments)) {
    echo "Команда не вказана. Використовуйте ./console <команда> [параметри]\n";
    exit(1);
}

// Виконання команди
try {
    $app->runCommand($arguments);
} catch (Exception $e) {
    echo 'Помилка: ' . $e->getMessage() . "\n";
    exit(1);
}